// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwNp9RwA5dPlxgH2YX9GKxU3tj_VMM-U',
    appId: '1:763695934346:web:0fb829c82df6e23f67f673',
    messagingSenderId: '763695934346',
    projectId: 'push-notification-43e80',
    authDomain: 'push-notification-43e80.firebaseapp.com',
    storageBucket: 'push-notification-43e80.appspot.com',
    measurementId: 'G-NJJWVTQBXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-CAyEwe1S_Gxr2IvssPX3-GeeF03--6E',
    appId: '1:763695934346:android:911fba0135f6113d67f673',
    messagingSenderId: '763695934346',
    projectId: 'push-notification-43e80',
    storageBucket: 'push-notification-43e80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqQfQPA1Wzv3yvXTl-HOEbdjsydW7Tg0',
    appId: '1:763695934346:ios:a275679dca14757267f673',
    messagingSenderId: '763695934346',
    projectId: 'push-notification-43e80',
    storageBucket: 'push-notification-43e80.appspot.com',
    iosClientId: '763695934346-mmcua8fm3k6gqo5fljluh4q90vf75ss0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwqQfQPA1Wzv3yvXTl-HOEbdjsydW7Tg0',
    appId: '1:763695934346:ios:a275679dca14757267f673',
    messagingSenderId: '763695934346',
    projectId: 'push-notification-43e80',
    storageBucket: 'push-notification-43e80.appspot.com',
    iosClientId: '763695934346-mmcua8fm3k6gqo5fljluh4q90vf75ss0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
